#!/usr/bin/env bash
set -e

input=$1
pkg=$2

echo "package $pkg"
echo

echo "// @generated by $0" "$@"

{
    grep 'Key.*= 0x80 | Key(terminfo' "$input" | awk '{print $1}'
    grep -A100 'MouseLeft Key =' "$input" | grep -o 'Mouse[a-zA-Z]*'
} | {
    echo
    echo 'var specialOffs = [][2]int{'
    off=0
    while read -r key; do
        str="<${key#Key*}>"
        next=$(( off + ${#str} ))
        echo "{$off, $next}, // ${key#Key*}"
        off=$next
    done
    echo '}'
}

{
    grep 'Key.*= 0x80 | Key(terminfo' "$input" | awk '{print $1}'
    grep -A100 'MouseLeft Key =' "$input" | grep -o 'Mouse[a-zA-Z]*'
} | {
    echo
    last='const specialTable = ""'
    while read -r key; do
        str="<${key#Key*}>"
        echo "$last +"
        last="\`$str\`"
    done
    echo "$last"
}
