package termkey

// @generated by ./scripts/gen_special_strings.sh key.go termkey

var specialOffs = [][2]int{
	{0, 4},     // F1
	{4, 8},     // F2
	{8, 12},    // F3
	{12, 16},   // F4
	{16, 20},   // F5
	{20, 24},   // F6
	{24, 28},   // F7
	{28, 32},   // F8
	{32, 36},   // F9
	{36, 41},   // F10
	{41, 46},   // F11
	{46, 51},   // F12
	{51, 59},   // Insert
	{59, 67},   // Delete
	{67, 73},   // Home
	{73, 78},   // End
	{78, 86},   // PageUp
	{86, 96},   // PageDown
	{96, 100},  // Up
	{100, 106}, // Down
	{106, 112}, // Left
	{112, 119}, // Right
	{119, 130}, // MouseLeft
	{130, 143}, // MouseMiddle
	{143, 155}, // MouseRight
	{155, 169}, // MouseRelease
	{169, 183}, // MouseWheelUp
	{183, 199}, // MouseWheelDown
	{199, 215}, // MouseWheelDown
}

const specialTable = "" +
	`<F1>` +
	`<F2>` +
	`<F3>` +
	`<F4>` +
	`<F5>` +
	`<F6>` +
	`<F7>` +
	`<F8>` +
	`<F9>` +
	`<F10>` +
	`<F11>` +
	`<F12>` +
	`<Insert>` +
	`<Delete>` +
	`<Home>` +
	`<End>` +
	`<PageUp>` +
	`<PageDown>` +
	`<Up>` +
	`<Down>` +
	`<Left>` +
	`<Right>` +
	`<MouseLeft>` +
	`<MouseMiddle>` +
	`<MouseRight>` +
	`<MouseRelease>` +
	`<MouseWheelUp>` +
	`<MouseWheelDown>` +
	`<MouseWheelDown>`
